version: '3.8' # Using version 3.8 to support Docker secrets

services:
  nginx:
    container_name: nginx
    image: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    env_file:
      - ".env"
    restart: always
    volumes:
      - wordpress_files:/var/www/html
    ports:
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - web

  mariadb:
    container_name: mariadb
    image: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    env_file:
      - ".env"
    secrets:
      - db_user
      - db_root_password
      - db_password
    volumes:
      - wordpress_data:/var/lib/mysql
    networks:
      - web
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  wordpress:
    container_name: wordpress
    image: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    env_file:
      - ".env"
    secrets:
      - db_user
      - db_password
      - wp_admin_password
      - wp_auth_key
      - wp_secure_auth_key
      - wp_logged_in_key
      - wp_nonce_key
      - wp_auth_salt
      - wp_secure_auth_salt
      - wp_logged_in_salt
      - wp_nonce_salt
    volumes:
      - wordpress_files:/var/www/html
    networks:
      - web
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy

  redis:   # Bonus: Redis cache
    container_name: redis
    image: redis
    build:
      context: ./requirements/redis
      dockerfile: Dockerfile
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - web

  ftp:     # Bonus: FTP server
    container_name: ftp
    image: ftp
    build:
      context: ./requirements/ftp
      dockerfile: Dockerfile
    restart: always
    volumes:
      - wordpress_files:/var/www/html
    ports:
      - "21:21"
      - "21100-21110:21100-21110" # for passive mode, TODO: need to think: should I open this ports?
    secrets:
      - ftp_password
    networks:
      - web
    depends_on:
      - wordpress

  adminer:  # Bonus: Adminer
    container_name: adminer
    image: adminer
    build:
      context: ./requirements/adminer
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    networks:
      - web
    depends_on:
      - mariadb

networks:
  web:
    driver: bridge
    name: inception_network

volumes:
  wordpress_data:
  wordpress_files:

secrets:
  db_user:
    file: ../secrets/db_user.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_auth_key:
    file: ../secrets/wp_auth_key.txt
  wp_secure_auth_key:
    file: ../secrets/wp_secure_auth_key.txt
  wp_logged_in_key:
    file: ../secrets/wp_logged_in_key.txt
  wp_nonce_key:
    file: ../secrets/wp_nonce_key.txt
  wp_auth_salt:
    file: ../secrets/wp_auth_salt.txt
  wp_secure_auth_salt:
    file: ../secrets/wp_secure_auth_salt.txt
  wp_logged_in_salt:
    file: ../secrets/wp_logged_in_salt.txt
  wp_nonce_salt:
    file: ../secrets/wp_nonce_salt.txt
  ftp_password:
    file: ../secrets/ftp_password.txt
